packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
